use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
	'NAME'            => "Debug::MessageArray",
	'VERSION_FROM'    => "MessageArray.pm", # finds $VERSION
	'PREREQ_PM'       => {
		'Data::Default' => 0.1,
		'String::Util' => 1.01,
		'Digest::MD5' => 2.36,
		'Debug::ShowStuff' => 1.1,
		'XML::Parser' => 2.34,
	}, # e.g., Module::Name => 1.1
	
	# Add these new keywords supported since 5.005
	(
		$] >= 5.005 ?
			(
				ABSTRACT_FROM  => "MessageArray.pm", # retrieve abstract from module
				AUTHOR         => "Miko O'Sullivan <miko\@idocs.com>"
			) :
			
			()
	),
);
